version: '3'

# docker volume create --name=pgdata

services:
  api:
    image: exchange-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange-api
    command: bash -c "npm run start:prod"
    restart: always
    volumes:
      - .:/app
    working_dir: '/app'
    ports:
      - '80:3000'
    depends_on:
      - 'postgres'
    networks:
      exchange-network:
        ipv4_address: 1.0.0.2

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nest-tdd
    networks:
      exchange-network:
        ipv4_address: 1.0.0.3

networks:
  exchange-network:
    driver: bridge
    ipam:
      config:
        - subnet: 1.0.0.0/24

volumes:
  pgdata:
    external: true